FROM alpine:3.20

ARG PB_VERSION=0.25.9

RUN apk add --no-cache \
    ca-certificates \
    unzip \
    wget \
    tzdata

RUN wget https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip \
    && unzip pocketbase_${PB_VERSION}_linux_amd64.zip -d /pb/ \
    && rm pocketbase_${PB_VERSION}_linux_amd64.zip \
    && chmod +x /pb/pocketbase

WORKDIR /pb

COPY pb_migrations /pb/pb_migrations
RUN ln -s /pb/pb_migrations /pb_migrations

EXPOSE 8090

VOLUME /pb_data

CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb_data", "--migrationsDir=/pb/pb_migrations"]


