import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language ts ./`.

export type Types = Models.Row & {
    code: string;
    description: string;
}

export type Categories = Models.Row & {
    code: string;
    type: Types;
    description: string;
    icon: string;
}

export type SubCategories = Models.Row & {
    code: string;
    description: string;
    icon: string;
    category: Categories;
    budget: number | null;
}

export type Transactions = Models.Row & {
    date: string;
    refundsIds: string | null;
    value: number;
    netValue: number | null;
    description: string | null;
    niceDescription: string;
    subCategory: SubCategories;
}

export type BankSessions = Models.Row & {
    sessionId: string;
    bankName: string | null;
    country: string | null;
    accounts: string[] | null;
    validUntil: string | null;
    status: string | null;
}

